columnSuffix: null
handle: richContent
instructions: null
name: 'Rich Content'
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: 3c1309a8-4142-4884-8c10-87bbf7968711 # Simple
  createButtonLabel: null
  defaultTransform: null
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
