color: null
fieldLayouts:
  2440c542-6181-4da7-a1d5-708624fdef69:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-06T17:49:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: bb5da4b7-97da-40ce-b7bd-b0c99cb58662
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-06T17:49:50+00:00'
            elementCondition: null
            fieldUid: deea1f26-8e02-440d-bc87-bc667b3a629b # Quote
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e503b524-5d3c-41f4-8662-06f531e731ac
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-06T19:33:00+00:00'
            elementCondition: null
            fieldUid: 2d0f1a10-6be3-46ff-8cce-097551af1b7b # Citation
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aa60e91a-3f37-4977-b589-b6507e2ba666
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4f1608cc-648b-4203-bf9c-360db5f6bada
        userCondition: null
handle: blockquote
hasTitleField: false
icon: quotes
name: Blockquote
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
