color: sky
fieldLayouts:
  4bce465d-a2b4-45b2-8150-04220b87abff:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-06T17:49:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 382a3896-70d6-4ce5-8003-1c6efc705b93
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-06T17:49:50+00:00'
            elementCondition: null
            fieldUid: c754f218-e9d4-427a-8883-104a5bf39528 # Book Author
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 73a7952e-dd72-4d6a-a514-a4432931dac6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-06T17:49:50+00:00'
            elementCondition: null
            fieldUid: fedbc754-a6c8-437a-aa0e-7103972762c9 # Published Year
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8b3411fd-92b8-4bb4-a3b0-09f7386bdee2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-06T17:49:50+00:00'
            elementCondition: null
            fieldUid: 3bacf350-5d8e-41b5-a2a2-eabd1c3f82d8 # BookCover
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ddedb613-f62c-4747-811d-7003dcd6e6f9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-06T17:49:50+00:00'
            elementCondition: null
            fieldUid: 24e21415-b3d1-49cb-8e99-54b8b0abb95e # Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6107c6d3-f577-4071-bacd-020e4ff27f28
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-06T17:49:50+00:00'
            elementCondition: null
            fieldUid: a2b13a80-c6af-4cbc-8d6e-a591c1e9d2fa # Longform Content
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 587b3f33-3f6a-4ca1-b7dc-d52eb42da161
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-07T00:44:13+00:00'
            elementCondition: null
            fieldUid: 3fff4b8c-88f8-4080-9187-c446bc9119c1 # Download
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c1045d96-e374-4795-a3ae-1a2a9927ec54
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 83820504-2e78-4356-b0c4-56228d8dda61
        userCondition: null
handle: book
hasTitleField: true
icon: book
name: Book
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
