color: null
fieldLayouts:
  4282094d-a9c7-430c-b502-adf1bd5bad88:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-06T18:25:08+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 8dc89fed-5104-4559-9c2e-32371b02b1e6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-06T18:26:24+00:00'
            elementCondition: null
            fieldUid: ed67c01c-23bc-42c9-9d71-fc6a4195951c # Address
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 98039bff-6605-46c2-9ebe-598d23ed32e4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-06T18:29:58+00:00'
            elementCondition: null
            fieldUid: 016740df-078c-4322-b1ca-c53663b47c4f # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bb00edda-33f3-4236-954a-9fd707b1c9eb
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: edb180e0-19f7-4425-aebe-7ac834733a31
        userCondition: null
handle: hotSpot
hasTitleField: true
icon: null
name: 'Hot Spot'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
