color: null
fieldLayouts:
  62917a1f-d7c2-4e8f-a49e-786832a76e31:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-06T17:49:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 76e08110-01a7-4170-ac4a-4057b4dec20c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-06T17:49:50+00:00'
            elementCondition: null
            fieldUid: c754f218-e9d4-427a-8883-104a5bf39528 # Book Author
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e0931560-d706-470b-9fb1-5a8b3633fd0d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-06T17:49:50+00:00'
            elementCondition: null
            fieldUid: fedbc754-a6c8-437a-aa0e-7103972762c9 # Published Year
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e750e19b-3aac-4ce3-b223-b22dd3a99fc1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-06T17:49:50+00:00'
            elementCondition: null
            fieldUid: 3bacf350-5d8e-41b5-a2a2-eabd1c3f82d8 # BookCover
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ad0c99b6-9bd9-40a1-9023-fbe6b00b0b25
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-06T17:49:50+00:00'
            elementCondition: null
            fieldUid: 3b874cdd-235e-4c88-9d4f-489d9c960b44 # Markdown
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d2bca8ff-3831-4143-9e20-170c1c55bae3
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 41f011b5-2031-4b81-9f84-8dd7dffb3289
        userCondition: null
handle: item
hasTitleField: true
icon: book
name: Item
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
