color: null
fieldLayouts:
  cc5fe58e-0120-4e90-afbe-48149442251d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-06T17:49:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e07f541f-0a6d-441c-87ea-728e17bc1e5b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-06T17:49:50+00:00'
            elementCondition: null
            fieldUid: ed67c01c-23bc-42c9-9d71-fc6a4195951c # Address
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a16b162c-2c03-43a2-af44-d20b6a501737
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 66910a2c-17de-4639-a5f3-4c7ec95107cd
        userCondition: null
handle: map
hasTitleField: true
icon: compass-drafting
name: Map
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
