defaultPlacement: end
enableVersioning: true
entryTypes:
  - 161cd8f7-15f0-40c3-8a3f-e5d724a86f4f # Homepage
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  d18c4377-f7e9-4de2-8d05-bc52b6bbbf55: # 10 Tower Mews
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
