baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: '10 Tower Mews'
primary: true
siteGroup: 6639307a-8f0d-43f9-8975-fe752c12a0ed # Craft 5 Boilerplate
sortOrder: 1
