altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  668af72e-3261-4876-af7b-7699c9e24a42:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 8b33be06-c544-4a39-9a92-c2e9347bc85a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 16151d14-b7b0-4249-b12d-ba3be20f1bc7 # Optimized Image (768w,640w,480w)
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2996ae99-2632-479c-8135-40b968b5d1e4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5a037c67-226f-4983-9e91-91dbabfa3688
        userCondition: null
fs: photos
handle: photos
name: Photos
sortOrder: 3
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
