color: null
fieldLayouts:
  e1437445-c396-4a58-b557-fbda44f6271b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d0574d67-ccfd-4a0c-8863-bf53be903271
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: c345e99f-8b30-4f6c-a7e1-a87492c6bca5
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 939db36c-b873-4572-9940-9cf57d832148
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3715413b-3465-4cd0-b1d7-39f2fc32235a
        userCondition: null
handle: coverImage
hasTitleField: false
icon: image
name: 'Cover Image'
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
