color: null
fieldLayouts:
  1ab6bd02-1240-407d-9c81-f117e71cfb46:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 496038a6-8d14-449c-8c01-cff1b6c208a1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 3b874cdd-235e-4c88-9d4f-489d9c960b44 # Markdown
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2dbd28e1-f01f-458a-ab2d-6c0de0bbfd9a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: db490998-4187-455b-9d87-ecc31503d9bb # New Book
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f803437f-a83d-48b8-9015-71f084919c99
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 776bf723-1222-42bd-b3f8-2f537e5f0b0d
        userCondition: null
handle: markdown
hasTitleField: true
icon: paragraph
name: Markdown
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
