altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  668af72e-3261-4876-af7b-7699c9e24a42:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-08-06T17:49:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 8b33be06-c544-4a39-9a92-c2e9347bc85a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-06T17:49:50+00:00'
            elementCondition: null
            fieldUid: e7a8d203-6365-4e81-a7e3-bf9b4f8952bb # Optimized Photo (768w,480w)
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db447f00-4ca2-4229-86cb-69e7f3e1cdf2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-20T19:45:45+00:00'
            elementCondition: null
            fieldUid: 0c15de54-9539-4fc4-b25a-f42898dcc946 # Optimized Blog
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 8eb5a7ca-bba3-4fdf-81f9-02ea0ec07eae
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-08-20T20:05:55+00:00'
            elementCondition: null
            fieldUid: 16151d14-b7b0-4249-b12d-ba3be20f1bc7 # Optimized Image (1200w,640w,480w)
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7baf1b0a-533f-47a5-a76e-5ea92a54a1b4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5a037c67-226f-4983-9e91-91dbabfa3688
        userCondition: null
fs: photos
handle: photos
name: Photos
sortOrder: 3
subpath: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
