columnSuffix: null
handle: download
instructions: null
name: Download
searchable: false
settings:
  maxLength: 255
  showLabelField: false
  showTargetField: false
  types:
    - url
    - entry
translationKeyFormat: null
translationMethod: none
type: craft\fields\Link
