columnSuffix: null
handle: optimizedCoverSmall
instructions: null
name: 'Optimized Cover Small'
searchable: false
settings:
  displayDominantColorPalette: false
  displayLazyLoadPlaceholderImages: true
  displayOptimizedImageVariants: true
  variants:
    -
      __assoc__:
        -
          - width
          - '325'
        -
          - useAspectRatio
          - ''
        -
          - aspectRatioX
          - '16'
        -
          - aspectRatioY
          - '9'
        -
          - retinaSizes
          -
            - '1'
        -
          - quality
          - '82'
        -
          - format
          - jpg
translationKeyFormat: null
translationMethod: none
type: nystudio107\imageoptimize\fields\OptimizedImages
