columnSuffix: null
handle: optimizedPhoto
instructions: null
name: 'Optimized Photo (768w,480w)'
searchable: false
settings:
  displayDominantColorPalette: false
  displayLazyLoadPlaceholderImages: true
  displayOptimizedImageVariants: true
  fieldVolumeSettings:
    __assoc__:
      -
        - photos
        - '*'
  variants:
    -
      __assoc__:
        -
          - width
          - '480'
        -
          - useAspectRatio
          - '1'
        -
          - aspectRatioX
          - '4'
        -
          - aspectRatioY
          - '3'
        -
          - retinaSizes
          -
            - '1'
        -
          - quality
          - '82'
        -
          - format
          - jpg
translationKeyFormat: null
translationMethod: none
type: nystudio107\imageoptimize\fields\OptimizedImages
