defaultPlacement: end
enableVersioning: true
entryTypes:
  - fa1f735b-d09f-480a-b4e2-a8ce0d80bc78 # Blog
handle: blogIndex
maxAuthors: 1
name: 'Blog Index'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  d18c4377-f7e9-4de2-8d05-bc52b6bbbf55: # 10 Tower Mews
    enabledByDefault: true
    hasUrls: true
    template: blog/index.twig
    uriFormat: blog
type: single
