defaultPlacement: end
enableVersioning: true
entryTypes:
  - a4d3998f-1664-4044-a128-b275085d0973 # ContactForm Header
handle: siteContact
maxAuthors: 1
name: 'Site Contact'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  d18c4377-f7e9-4de2-8d05-bc52b6bbbf55: # 10 Tower Mews
    enabledByDefault: true
    hasUrls: true
    template: contact/contact.twig
    uriFormat: contact
type: single
