tabs:
  -
    elementCondition: null
    elements:
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        dateAdded: '2025-01-11T12:31:32-05:00'
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\addresses\LabelField
        uid: 69486bd8-fe26-4569-a2d9-8ba0fb332b16
        userCondition: null
        warning: null
        width: 100
      -
        attribute: countryCode
        dateAdded: '2025-01-11T12:31:32-05:00'
        elementCondition: null
        id: null
        includeInCards: false
        instructions: null
        label: null
        orientation: null
        providesThumbs: false
        requirable: false
        tip: null
        type: craft\fieldlayoutelements\addresses\CountryCodeField
        uid: 1baa757e-d458-4d92-a2d6-c984f6e0684a
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2025-01-11T12:31:32-05:00'
        elementCondition: null
        includeInCards: true
        instructions: null
        label: null
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\addresses\AddressField
        uid: 9f2b5b08-cef6-45e6-9913-a984ef902ae6
        userCondition: null
        warning: null
    name: Content
    uid: 0cf1673f-de37-4619-868a-ffc45b46ddfb
    userCondition: null
