tabs:
  -
    elementCondition: null
    elements:
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        dateAdded: '2024-12-04T18:18:33-05:00'
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\addresses\LabelField
        uid: b7a0fd5d-9732-43d8-a5af-6cf3aec07541
        userCondition: null
        warning: null
        width: 100
      -
        attribute: countryCode
        dateAdded: '2024-12-04T18:18:33-05:00'
        elementCondition: null
        id: null
        includeInCards: false
        instructions: null
        label: null
        orientation: null
        providesThumbs: false
        requirable: false
        tip: null
        type: craft\fieldlayoutelements\addresses\CountryCodeField
        uid: 0ba70a50-3d65-4f51-a633-b75993d5c45c
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2024-12-04T18:18:33-05:00'
        elementCondition: null
        includeInCards: true
        instructions: null
        label: null
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\addresses\AddressField
        uid: a1c50080-ec67-442e-8fe0-417d28a04f65
        userCondition: null
        warning: null
    name: Content
    uid: 0b996041-84c6-4493-ac7d-e86e32878e16
    userCondition: null
